sudo: false
language: node_js
node_js:
  - "8.9"
cache:
  yarn: true
  directories:
    - node_modules

# exclude tags
branches:
  only:
    - master

env:
  global:
    # build number used by Makefile and Coveralls
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

before_script:
  - npm rebuild node-sass #need to rebuild here https://github.com/sass/node-sass/issues/1387#issuecomment-185451183
  - yarn run storybook-static
  - git diff --exit-code yarn.lock

script:
  - yarn test:ci

after_success:
  - npm run coveralls
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export GIT_TAG=$(make version) ||
    export GIT_TAG=$(make version)-beta
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export NPM_TAG=latest ||
    export NPM_TAG=beta
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - >
    [ "${TRAVIS_BRANCH}" != "master" ] &&
    echo "skipping versioning" ||
    yarn run build &&
    npm version $GIT_TAG -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID" &&
    # git push --tags git@github.com:$TRAVIS_REPO_SLUG.git &&
    npm publish --tag $NPM_TAG

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   local_dir: .storybook-out/
   verbose: true
   on:
      branch: master

