sudo: false
language: node_js
node_js:
  - "7.7.1"
cache:
  yarn: true
  directories:
    - node_modules

# exclude tags
branches:
  only:
    - master

env:
  global:
    # build number used by Makefile and Coveralls
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - secure: "DTA/wJ8Z0AMMnCtzokJoAeFWC45FrJNZJIx+2V7esCqdNMTg3vNbbcCdthm2qw/Lgu8SbstzBqGiaaHwvTUoy3y4Kk38T+Fx8uGbfbl7NMN/f/TaxiSJuEHaBgz0ot29EfjIljnxaTLBZY9ADOr8j+jLnJMwBybKzmZcRuRXFE02+Zqvj/UhIBW46KurjMWzcySvIre4wZAIpsff7X9tHpK4y0/1dyo6QEpn/WAuDBB5ueBypZvQvsKRM+PwWR9YuByxHfPtVdAE2sUUFnVFJofWwFrOOtz1fQ8Vp259gEBEXEAVzSifMcItXudXNCcM8Hy4H9IrrNd8gkztSm8pssvjkLhsinTbb+UeGxVEHOQUojAcFHFAThiNGEV1GV7sY1fEBoujgRtlUQJaCBsW4boAwNElsJq3tKJ5Vj/FSaiE58uKjS2FItrvAKiNTe9TUPGTxEiFfbKDH6wmEiYXB33Ra3aoYv68ZEBpLdLHKMIBXoC+QgGsQEEPj8PC8gkBQ7josTJD8UkPQA8L29WUkyPw/TcWb4F6myiUqms2wKfwtuGobDV867dUQy2WxT3h4N5uNRNeirR8mXJdbGdzTg0KgJm1FNKjmewae/n97B+604eQgz4NLqI2pOaaZm5nqqqG3ItzuURuNNBZmL8xGH4VIGH6xJu+6frdDxhssNk="

before_install:
  - openssl aes-256-cbc -K $encrypted_9064aff2eda1_key -iv $encrypted_9064aff2eda1_iv -in '.travis/github_deploy_key.enc' -out github_deploy_key -d
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

before_script:
  - git diff --exit-code yarn.lock

after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - $(yarn bin)/set-up-ssh --key "$encrypted_9064aff2eda1_key" --iv "$encrypted_9064aff2eda1_iv" --path-encrypted-key ".travis/github_deploy_key.enc"
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export GIT_TAG=$(make version) ||
    export GIT_TAG=$(make version)-beta
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export NPM_TAG=latest ||
    export NPM_TAG=beta
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - >
    [ "${TRAVIS_BRANCH}" != "master" ] &&
    echo "skipping versioning" ||
    yarn run build &&
    npm version $GIT_TAG -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID" &&
    git push --tags git@github.com:$TRAVIS_REPO_SLUG.git &&
    npm publish --tag $NPM_TAG

after_success:
  - npm run coveralls

notifications:
  # slack integration
  slack:
    # encrypted token for the meetuphq slack channel
    secure: "oW5B1Yow4dWFo8taSIcnR6PJX+V8SC1Af0Irec6JpfEDzKD4oFxY4UliROXKNiZzNHY4qqwtFGr9JSnHzQtnllhjD3RPwzlDYvwMXRrv2BYiQIX4Cod8P/SjjWPCX2j9qMijAVtViY+m5/OYK60/N5K+h0OS9KIhSl1NDJpDOsGDB+WZOVycHX3F6a3rSThgNaN8Ln34CqoFDmbidsYpuW3TP4QXbDbvT8bBnWyxWBgyOKEclUtyGGYCBuNjNEz7mfgEGAVqrLeyQANBu5BEoyP9n473LDHeM18IDbUh4yju1vAM5J/PPMiotoFcNR1ldEYKgoOcODONIQ7X6z9/1u7tA2AnJKkMZkFOJ3dLg+fGx8yTPO+jKUY0x0g7h1lsw0Re4GCyPuAlRTCYuWK1hvqIUEIhbPQF+XAFrhHcv1Ua5N7HHw2Nlu62q/j85GQHyKiWvu/FFM2TSEne+vA1DjliYLwhaNhiG6zVGKfEC2cM7yHtGxBhKrnKDw/wpBGn0d9hVVmmULJU2IZA/OmtvU/4o9nbSBWVHzGkmxgOL//6pRy67yORpsvtkffZFic2IN4GIcSuvgOLPvGtfSq44FW5wmEn6DuHihTHKfuIzZ3KjLgzwwFtNtVm2laxTds/PyG1zurIPN2mRVnms5ms/vbV9wErSm/Z0gAj74uB4sc="

